source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'WeChatSDKPods_Example', :exclusive => true do
  pod "WeChatSDKPods", :path => "../"
end

target 'WeChatSDKPods_Tests', :exclusive => true do
  pod "WeChatSDKPods", :path => "../"

  
end
